server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.17.137:3306/oauth-center
    username: root
    password: root
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 172.17.17.192
    port: 16386
    password: redis16386
    database: 11