server:
  port: 7002
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #是否需要注册
        register: true
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}:${server.port}-1
        #服务的名称
        service-name: ${spring.application.name}
        #服务的请求端口
        port: ${server.port}
        #健康检查路径
        healthCheckPath: /actuator/health
        #健康检查时间间隔
        healthCheckInterval: 15s
        #开启ip地址注册
        prefer-ip-address: true
        #实例的请求ip
        ip-address: ${spring.cloud.client.ip-address}
service-url:
  consul-user-service: http://consul-user-service
management:
  endpoints:
    web:
      exposure:
        include: '*'