server:
  port: 9301
spring:
  application:
    name: retrofit-service
  cloud:
    nacos:
      discovery:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9 
        server-addr: 172.17.17.137:8848 #配置Nacos地址
    sentinel:
      transport:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9 
        dashboard: 172.17.17.137:6999 #配置sentinel dashboard地址
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
retrofit:
  log:
    # 启用日志打印
    enable: true
    # 日志打印拦截器
    logging-interceptor: com.github.lianjiatech.retrofit.spring.boot.interceptor.DefaultLoggingInterceptor
    # 全局日志打印级别
    global-log-level: info
    # 全局日志打印策略
    global-log-strategy: body
  # 熔断降级配置
  degrade:
    # 是否启用熔断降级
    enable: true
    # 熔断降级实现方式
    degrade-type: sentinel
    # 熔断资源名称解析器
    resource-name-parser: com.github.lianjiatech.retrofit.spring.boot.degrade.DefaultResourceNameParser