server:
  port: 4001
spring:
  application:
    name: zookeeper-ribbon-service
  cloud:
    zookeeper:
      # zookeeper连接地址
      connect-string: 172.17.17.137:2181
      discovery:
        # 作为服务注册
        register: true
        # 注册时使用IP地址而不是hostname
        prefer-ip-address: true
service-url:
  user-service: http://zookeeper-user-service