server:
  port: 9006
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9 
        server-addr: 172.17.17.137:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'