server:
  port: 5001
spring:
  profiles:
    active: dev
  application:
    name: xzh-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.17.137:8848
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9
    gateway:
      routes: #配置路由路径
        - id: user-service
          uri: lb://user-center
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-center
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
xzh:
  swagger-agg:
    generate-routes: user-service,order-service