server:
  port: 8081

spring:
  application:
    name: portal

zlt:
  sso:
    client-id: portal
    client-secret: 123456
    redirect-uri: http://127.0.0.1:8081/callback.html
    access-token-uri: http://127.0.0.1:8080/oauth/token
    user-info-uri: http://127.0.0.1:8080/oauth/users/current