server:
  port: 9000
spring:
  application:
    name: admin-server
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: admin
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9 
        server-addr: 172.17.17.137:8848