server:
   port: 7101
spring:
  application:
    name: nacos-dubbo-consumer
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9 
        server-addr: 172.17.17.137:8848 #Nacos地址
dubbo:
   registry:
      address: spring-cloud://172.17.17.137:8848 # 注册中心
   cloud:
      subscribed-services: nacos-dubbo-provider  # 订阅的提供者名称