server:
  port: 9902
spring:
  profiles:
    active: dev
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.17.137:8848
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9
management:
  endpoints:
    web:
      exposure:
        include: "*"
