server:
  port: 9005
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9
        server-addr: 172.17.17.137:8848 #配置Nacos地址
    sentinel:
      transport:
        dashboard: 172.17.17.137:6999 #配置sentinel dashboard地址
        port: 8719
      datasource:
        ds1:
          nacos:
            namespace: 52c42c43-adae-4f52-91d0-7bdaf28d2ac9
            server-addr: 172.17.17.137:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
feign:
  sentinel:
    enabled: true #打开sentinel对feign的支持
resttemplate:
  sentinel:
    enabled: true #打开@SentinelRestTemplate注解
service-url:
  user-service: http://user-service
management:
  endpoints:
    web:
      exposure:
        include: '*'