server:
   port: 8090
dubbo:
   registry:
      address: spring-cloud://xuzhihao # 注册中心
   cloud:
      subscribed-services: sc-dubbo-provider # 订阅的提供者名称
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always