server:
  port: 8801
spring:
  application:
    name: gateway-server
  cloud: #配置SpringCloudGateway的路由
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/user-server/**
        filters:
          - PreserveHostHeader
          - RewritePath=/user-server/(?<segment>.*), /$\{segment}
      - id: feign-service
        uri: lb://feign-service
        predicates:
          - Path=/feign-service/**
        filters:
          - StripPrefix=1
          - PreserveHostHeader
eureka:
   instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
      lease-renewal-interval-in-seconds: 5 #每隔几秒告诉eureka服务器我还存活，用于心跳检测 默认30 
      lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除 默认90
   client:
      healthcheck:
         enabled: false
      serviceUrl:
         defaultZone: http://admin:admin@127.0.0.1:9001/eureka/
logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000